# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('action', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeTask', models.CharField(max_length=10)),
                ('task', models.TextField()),
                ('date', models.DateField()),
                ('sender', models.TextField()),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('mailer', models.CharField(max_length=10)),
                ('threadID', models.TextField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsNotification', models.BooleanField(default=False)),
                ('appNotification', models.BooleanField(default=False)),
                ('browserNotification', models.BooleanField(default=False)),
                ('mobileForNotification', models.BigIntegerField(default=0)),
                ('mobileVerified', models.BooleanField(default=False)),
                ('timePer', models.IntegerField(default=5)),
                ('noOfMsg', models.IntegerField(default=50)),
                ('verCode', models.CharField(max_length=50)),
                ('varCodeTime', models.DateTimeField(auto_now_add=True)),
                ('timeOfNotification', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('refresh_token', models.CharField(max_length=254)),
                ('picture', models.TextField()),
                ('login_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
