# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dailyschedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.EmailField(default='dev.mailassist@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
